blank_issues_enabled: false
contact_links:
  - name: Hanzo S3 Community Support
    url: https://github.com/hanzos3/operator/discussions
    about: Please ask and answer questions here.
  - name: Hanzo S3 Enterprise Support
    url: https://hanzo.ai/pricing
    about: Contact us for enterprise support.
