apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator
commonAnnotations:
  operator.min.io/authors: "Hanzo AI, Inc."
  operator.min.io/license: AGPLv3
  operator.min.io/support: https://s3.hanzo.ai

resources:
  - resources/base/namespace.yaml
  - resources/base/service-account.yaml
  - resources/base/cluster-role.yaml
  - resources/base/cluster-role-binding.yaml
  - resources/base/crds/
  - resources/base/service.yaml
  - resources/base/deployment.yaml
