apiVersion: sts.min.io/v1beta1
kind: PolicyBinding
metadata:
  name: mc-job-binding
  namespace: hanzo-s3-tenant-1
spec:
  application:
    namespace: hanzo-s3-tenant-1
    serviceaccount: mc-job-sa
  policies:
    - consoleAdmin