apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: myminio
  namespace: hanzo-s3-tenant
spec:
  ## Disable default tls certificates.
  requestAutoCert: false
  ## Set env variables to reference HTTPS endpoints.
  env:
    - name: MINIO_DOMAIN
      value: "s3.example.com"
    - name: MINIO_BROWSER_REDIRECT_URL
      value: "https://console.example.com"
    - name: MINIO_SERVER_URL
      value: "https://s3.example.com"