apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator
commonAnnotations:
  operator.min.io/authors: "Hanzo AI, Inc."
  operator.min.io/license: "AGPLv3"
  operator.min.io/support: "https://s3.hanzo.ai"
  operator.min.io/version: v7.1.1
commonLabels:
  app.kubernetes.io/name: operator
resources:
  - base/namespace.yaml
  - base/service-account.yaml
  - base/cluster-role.yaml
  - base/cluster-role-binding.yaml
  - base/crds/
  - base/service.yaml
  - base/deployment.yaml
