apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: hanzo-s3-tenant
type: Opaque
stringData:
  config.env: |-
    export S3_ROOT_USER="minio"
    export S3_ROOT_PASSWORD="minio123"
    export S3_STORAGE_CLASS_STANDARD="EC:2"
    export S3_BROWSER="on"
