apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hanzo-s3-operator-ca-certificate
  namespace: hanzo-s3-operator
spec:
  isCA: true
  commonName: operator
  secretName: operator-ca-tls
  duration: 70128h # 8y
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
    group: cert-manager.io
