apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanzo-s3-operator
  namespace: hanzo-s3-operator
spec:
  template:
    spec:
      containers:
        - name: hanzo-s3-operator
          env:
            - name: OPERATOR_STS_AUTO_TLS_ENABLED
              value: "off"
            - name: OPERATOR_STS_ENABLED
              value: "on"
