apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sts-certmanager-cert
  namespace: hanzo-s3-operator
spec:
  dnsNames:
    - sts
    - sts.hanzo-s3-operator.svc
    - sts.hanzo-s3-operator.svc.cluster.local
  secretName: sts-tls
  issuerRef:
    name: hanzo-s3-operator-ca-issuer
