apiVersion: v2
description: A Helm chart for Hanzo S3 Operator
name: operator
version: 7.1.1
appVersion: v7.1.1
keywords:
  - storage
  - object-storage
  - S3
home: https://s3.hanzo.ai
icon: https://hanzo.ai/icon.png
sources:
  - https://github.com/hanzos3/operator
maintainers:
  - name: Hanzo AI, Inc.
    email: dev@hanzo.ai
type: application
