apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: myminio
  namespace: hanzo-s3-tenant
spec:
  ## Add environment variables to be set in Hanzo S3 container (https://github.com/minio/minio/tree/master/docs/config)
  env:
    - name: S3_IDENTITY_OPENID_CONFIG_URL
      value: "https://your-extenal-idp.com/.well-known/openid-configuration" # Your external identity provide configuration
    - name: S3_IDENTITY_OPENID_CLIENT_ID
      value: "OPENID CLIENT ID"
    - name: S3_IDENTITY_OPENID_CLIENT_SECRET
      value: "OPENID CLIENT SECRET"
    - name: S3_IDENTITY_OPENID_SCOPES
      value: "openid,profile,email"
    - name: S3_IDENTITY_OPENID_CLAIM_NAME
      value: "https://s3.hanzo.ai/policy"
